### ISSUE TITLE
NPE when adding chips

### ISSUE THREAD

**Issue by arshad115** [fiskurgit/ChipCloud#47]
The chipcloud object is initialized and when adding chips from an array I get this error. I am using async task to add chips.

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at fisk.chipcloud.ChipCloud.addChip(ChipCloud.java:101)
        at fisk.chipcloud.ChipCloud.addChip(ChipCloud.java:88)
        at fisk.chipcloud.ChipCloud.addChip(ChipCloud.java:126)
        at fisk.chipcloud.ChipCloud.addChips(ChipCloud.java:79)
        at com.kookydroidapps.food.recipes.RecipeDetailActivity$loadCategories.onPostExecute(RecipeDetailActivity.java:1175)
        at com.kookydroidapps.food.recipes.RecipeDetailActivity$loadCategories.onPostExecute(RecipeDetailActivity.java:1165)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by arshad115** [comment]
Update: My bad, there was a null in the array. But there should be a null check in the library also?
